# Generated by Django 4.2.4 on 2024-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_button_clicked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status_inscriere',
        ),
        migrations.RemoveField(
            model_name='incarcarepdf',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='customuser',
            name='final_grade1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='final_grade2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incarcarepdf',
            name='declaratie',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='incarcarepdf',
            name='eseu',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='incarcarepdf',
            name='fisa_inregistrare',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='incarcarepdf',
            name='nume_student',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='incarcarepdf',
            name='prenume_student',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incarcarepdf',
            name='titlul_lucrarii',
            field=models.CharField(max_length=255),
        ),
    ]
