# Generated by Django 4.2.4 on 2024-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_last_button_clicked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='final_grade1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='final_grade2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grade1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grade2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_grade',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_reason',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='incarcarepdf',
            name='declaratie',
        ),
        migrations.RemoveField(
            model_name='incarcarepdf',
            name='eseu',
        ),
        migrations.RemoveField(
            model_name='incarcarepdf',
            name='fisa_inregistrare',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_button_clicked',
            field=models.CharField(choices=[('modify1', 'Aprobat'), ('modify2', 'In Asteptare'), ('modify3', 'Respins')], default='modify2', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nota',
            field=models.FloatField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_inscriere',
            field=models.CharField(choices=[('Aprobat', 'Aprobat'), ('Respins', 'Respins'), ('In asteptare', 'In Asteptare')], default='In asteptare', max_length=12),
        ),
        migrations.AddField(
            model_name='incarcarepdf',
            name='pdf_file',
            field=models.FileField(default=2, upload_to='pdfs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incarcarepdf',
            name='nume_student',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='incarcarepdf',
            name='prenume_student',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incarcarepdf',
            name='titlul_lucrarii',
            field=models.CharField(max_length=100),
        ),
    ]
