# Generated by Django 4.2.4 on 2024-06-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_final_grade1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incarcarepdf',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='incarcarepdf',
            name='declaratie_autenticitate',
            field=models.FileField(blank=True, null=True, upload_to='declarations/'),
        ),
        migrations.AddField(
            model_name='incarcarepdf',
            name='eseu',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='incarcarepdf',
            name='fisa_inscriere',
            field=models.FileField(blank=True, null=True, upload_to='registration_papers/'),
        ),
    ]
