# Generated by Django 4.2.4 on 2024-06-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rejectionreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionreason',
            name='reason',
            field=models.TextField(max_length=3000),
        ),
    ]
