# Generated by Django 4.2.4 on 2024-06-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_rejectionreason_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incarcarepdf',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RejectionReason',
        ),
    ]
