# Generated by Django 4.2.4 on 2024-07-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_last_button_clicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='afisare_note',
            field=models.BooleanField(default=False),
        ),
    ]
